# Generated by Django 4.2.3 on 2023-07-17 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_quitteruser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quitteruser",
            name="age",
            field=models.IntegerField(
                default=18, validators=[django.core.validators.MaxValueValidator(123)]
            ),
        ),
    ]
