# Generated by Django 4.2.3 on 2023-07-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_quitteruser_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="quitteruser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
