# Generated by Django 4.2.3 on 2023-07-18 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_quitteruser_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quitteruser",
            name="date_of_birth",
            field=models.DateField(
                blank=True, default=datetime.date(2000, 1, 1), null=True
            ),
        ),
    ]
