# Generated by Django 4.2.3 on 2023-07-23 11:17

import django.core.validators
from django.db import migrations, models
import quitter.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_quitteruser_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quitteruser",
            name="last_name",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    quitter.accounts.validators.only_letters,
                ],
            ),
        ),
    ]
