# Generated by Django 4.2.3 on 2023-07-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0003_alter_photos_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photos",
            name="published",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
