# Generated by Django 4.2.3 on 2023-07-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0004_alter_photos_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photos",
            name="url",
            field=models.URLField(max_length=1000),
        ),
    ]
