# Generated by Django 4.2.3 on 2023-07-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0006_alter_photos_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photos",
            name="url",
            field=models.URLField(max_length=1000),
        ),
    ]
