# Generated by Django 4.2.3 on 2023-07-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0007_alter_photos_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photos",
            name="url",
            field=models.URLField(max_length=2000),
        ),
    ]
