# Generated by Django 4.2.3 on 2023-07-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0009_alter_photos_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photos",
            name="about",
            field=models.TextField(max_length=780),
        ),
    ]
