# Generated by Django 4.2.3 on 2023-07-18 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0010_alter_photos_about"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photos",
            options={"verbose_name_plural": "Photos"},
        ),
    ]
