# Generated by Django 4.2.3 on 2023-07-18 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quits", "0003_alter_quit_tagged_people"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quit",
            name="tagged_people",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_people", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
