# Generated by Django 4.2.3 on 2023-07-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_remove_comment_for_quit_remove_like_for_photo_and_more"),
        ("quits", "0004_alter_quit_tagged_people"),
    ]

    operations = [
        migrations.AddField(
            model_name="quit",
            name="comments",
            field=models.ManyToManyField(
                blank=True, related_name="quits", to="common.comment"
            ),
        ),
        migrations.AddField(
            model_name="quit",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="quits", to="common.like"
            ),
        ),
    ]
