# Generated by Django 4.2.3 on 2023-07-18 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quits", "0005_quit_comments_quit_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quit",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="quit",
            name="likes",
        ),
    ]
