# Generated by Django 4.2.3 on 2023-07-18 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quits", "0006_remove_quit_comments_remove_quit_likes"),
        ("common", "0004_remove_comment_for_quit_remove_like_for_quit"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="for_quit",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="quits.quit"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="like",
            name="for_quit",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="quits.quit"
            ),
            preserve_default=False,
        ),
    ]
